### Login as ADMIN
POST http://{{host}}:{{port}}/{{version_api}}/{{auth}}/signin/
Content-Type: application/json

{
  "userName": "Admin",
  "password": "password"
}

> {% client.global.set("authorization", response.headers.valueOf("Authorization")); %}

###

### TEST  with telegram
GET http://{{host}}:{{port}}/{{version_api}}/{{auth}}

###

### login  with telegram
GET http://{{host}}:{{port}}/{{version_api}}/{{auth}}/100/

> {% client.global.set("auth_token", response.body.json.token); %}

###

### TEST  with telegram
GET http://{{host}}:{{port}}/{{version_api}}/{{auth}}/test
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZWxlZ3JhbVVzZXIxIiwicm9sZXMiOlsiQ0hST01FX0VYVEVOU0lPTiIsIlRFTEVHUkFNIl0sImlhdCI6MTYzODgwMzk0MCwiZXhwIjoxNjQxMzk1OTQwfQ._CL4U8Rn0VrVK7fKrGawG_I4GIhZ9dDDeJtvLUDHKLY

###{{auth_token}}
###
