### Login as ADMIN
POST http://{{host}}:{{port}}/{{version_api}}/{{auth}}/signin/
Content-Type: application/json

{
  "userName": "Admin",
  "password": "password"
}

> {% client.global.set("authorization", response.headers.valueOf("Authorization")); %}

###

### update organization with id
PUT http://{{host}}:{{port}}/{{version_api}}/chrome
Content-Type: application/json
Authorization: {{ authorization }}

{

}
###